DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS department;



CREATE TABLE department(
department_id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL 
);

CREATE TABLE role(
role_id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INTEGER,
FOREIGN KEY (department_id) REFERENCES department(department_id) ON DELETE CASCADE
);

CREATE TABLE employee(
employee_id INTEGER  AUTO_INCREMENT PRIMARY KEY NOT NULL,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
manager_id INTEGER,
role_id INTEGER,
FOREIGN KEY (role_id) REFERENCES role(role_id) ON DELETE CASCADE,
FOREIGN KEY (manager_id) REFERENCES employee(employee_id) ON DELETE SET NULL
);